version: '3'

services:
  mysql-plm:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=plm
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/plm:/var/lib/mysql

  mysql-product:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=product
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/product:/var/lib/mysql

  mysql-customer:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=customer
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/customer:/var/lib/mysql

  mysql-service:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "13309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=service
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - /Users/realimpact/Documents/swingdb/service:/var/lib/mysql

  prod:
    build: microservices/product-service/product-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    depends_on:
      mysql-product:
        condition: service_healthy

  plm:
    build: microservices/plm-service/plm-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    depends_on:
      mysql-plm:
        condition: service_healthy

  customer:
    build: microservices/customer-service/customer-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    depends_on:
      mysql-customer:
        condition: service_healthy

  service:
    build: microservices/service-service/service-server
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - TZ=Asia/Seoul
    depends_on:
      mysql-service:
        condition: service_healthy

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: spring-cloud/gateway
    mem_limit: 350m
    ports:
      - "8080:8080"

  eureka:
    build: spring-cloud/eureka-server
    mem_limit: 350m
